# Generated by Django 3.2.4 on 2021-08-06 12:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('SHORT', models.CharField(blank=True, max_length=10, null=True)),
                ('URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=40)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(default='+8801720274040', max_length=128, region=None)),
                ('Facebook_Link', models.URLField(blank=True, null=True)),
                ('Maximum_Education_Level', models.SmallIntegerField(choices=[(0, 'Class 0 or down'), (2, 'Class 2 or down'), (3, 'Class 3 or down'), (4, 'Class 4 or down'), (5, 'Class 5 or down'), (6, 'Class 6 or down'), (7, 'Class 7 or down'), (8, 'Class 8 or down'), (9, 'Class 9 or down'), (10, 'Class 10 or down'), (11, 'Class 11 or down'), (12, 'Class 12 or down'), (20, 'Others')], default=20)),
                ('Education_Medium', models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Arbi Medium'), (5, 'Arbi Version'), (6, 'Technical')], default=1)),
                ('Expertise', models.CharField(blank=True, max_length=150, null=True)),
                ('Gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('Type', models.SmallIntegerField(choices=[(1, 'Normal'), (1, 'Special')], default=1)),
                ('Running_Tuition', models.IntegerField(default=0)),
                ('Location0', models.CharField(blank=True, max_length=100, null=True)),
                ('Location1', models.CharField(blank=True, max_length=100, null=True)),
                ('Location2', models.CharField(blank=True, max_length=100, null=True)),
                ('Location3', models.CharField(blank=True, max_length=100, null=True)),
                ('Location4', models.CharField(blank=True, max_length=100, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Important_Note', models.TextField(blank=True, null=True)),
                ('Rating', models.IntegerField(blank=True, default=0, null=True)),
                ('BAN', models.BooleanField(default=False)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Avatar')),
                ('Certificate', models.ImageField(blank=True, null=True, upload_to='Certificate')),
                ('NID', models.ImageField(blank=True, null=True, upload_to='NID')),
                ('Reminder', models.DateTimeField(blank=True, null=True)),
                ('Graduation_Institute', models.ManyToManyField(blank=True, to='Teacher.University')),
            ],
        ),
    ]
