# Generated by Django 3.2.4 on 2021-08-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Graduation_Institute',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Graduation_Institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.university'),
        ),
    ]
