# Generated by Django 3.2.4 on 2021-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20210814_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=110, null=True)),
                ('SHORT', models.CharField(blank=True, max_length=10, null=True)),
                ('URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='Graduation_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.subject'),
        ),
    ]
