# Generated by Django 3.2.4 on 2021-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20210814_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='RatedPerson',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
