# Generated by Django 3.2.4 on 2021-08-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_teacher_ratedperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
