# Generated by Django 3.2.4 on 2021-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_alter_teacher_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'Normal'), (2, 'Special')], default=1),
        ),
    ]
