# Generated by Django 3.2.4 on 2021-08-26 06:24

import Teacher.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_alter_teacher_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Graduation_GPA',
            field=models.FloatField(blank=True, null=True, verbose_name=Teacher.models.Subject),
        ),
        migrations.AddField(
            model_name='teacher',
            name='HSC_GOLDEN',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='HSC_GPA',
            field=models.FloatField(blank=True, null=True, verbose_name=Teacher.models.Subject),
        ),
        migrations.AddField(
            model_name='teacher',
            name='HSC_Institute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='HSC_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='HSC_SUB', to='Teacher.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='SSC_GOLDEN',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='SSC_GPA',
            field=models.FloatField(blank=True, null=True, verbose_name=Teacher.models.Subject),
        ),
        migrations.AddField(
            model_name='teacher',
            name='SSC_Institute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='SSC_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SSC_SUB', to='Teacher.subject'),
        ),
    ]
