# Generated by Django 3.2.4 on 2021-08-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_auto_20210826_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Graduation_GPA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC_GPA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_GPA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
