# Generated by Django 3.2.4 on 2021-08-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0009_auto_20210828_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Location0',
            new_name='PermanentLocation',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Location1',
            new_name='PresentLocation',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Graduation_Institute',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Graduation_Subject',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.subject'),
        ),
    ]
