# Generated by Django 3.2.4 on 2021-08-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_auto_20210830_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.division'),
        ),
        migrations.AlterField(
            model_name='upzillamunicipality',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.district'),
        ),
    ]
