# Generated by Django 3.2.4 on 2021-08-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0013_auto_20210830_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upzillamunicipality',
            name='District',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='UpzillaMunicipality',
        ),
    ]
