# Generated by Django 3.2.4 on 2021-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0015_auto_20210830_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='Name',
            field=models.CharField(blank=True, default='Dhaka', max_length=150),
        ),
    ]
