# Generated by Django 3.2.4 on 2021-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0019_auto_20210902_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ExpectedSalary',
            field=models.IntegerField(blank=True, default=2500, null=True),
        ),
    ]
