# Generated by Django 3.2.4 on 2021-09-02 08:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0021_teacher_tuitionstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='BloodGroup',
            field=models.IntegerField(blank=True, choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')], null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Guardian_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
