# Generated by Django 3.2.4 on 2021-09-02 09:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0023_auto_20210902_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Refer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
