# Generated by Django 3.2.4 on 2021-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0024_teacher_refer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Education_Medium',
            new_name='Preferred_Medium',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Refer_Name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
