# Generated by Django 3.2.4 on 2021-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0026_alter_teacher_expectedsalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Maximum_Education_Level',
            new_name='Preferred_Education',
        ),
    ]
