# Generated by Django 3.2.4 on 2021-09-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0029_alter_teachingsection_preferred_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ExpectedSalary',
            field=models.IntegerField(blank=True, default=2500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Refer_Name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TuitionStyle',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Private'), (2, 'Group'), (3, 'Both')], default=2500, null=True),
        ),
    ]
