# Generated by Django 3.2.4 on 2021-09-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0030_auto_20210906_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='HSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teachingsection',
            name='Preferred_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='university',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
