# Generated by Django 3.2.4 on 2021-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0031_auto_20210906_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Title',
            field=models.CharField(blank=True, max_length=110, null=True, unique=True),
        ),
    ]
