# Generated by Django 3.2.4 on 2021-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0032_alter_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1, null=True),
        ),
    ]
