# Generated by Django 3.2.4 on 2021-09-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0034_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Age',
            field=models.IntegerField(blank=True, choices=[(0, '<20'), (1, '21-25'), (2, '26-35'), (3, '>35')], null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Religion',
            field=models.IntegerField(blank=True, choices=[(0, 'Islam'), (1, 'Hinduism '), (2, 'Buddhism '), (3, 'Christianity'), (4, 'Others')], null=True),
        ),
    ]
