# Generated by Django 3.2.4 on 2021-09-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0035_auto_20210909_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Last_Institute',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Last_Medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
