# Generated by Django 3.2.4 on 2021-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0036_auto_20210914_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TuitionStyle',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Private'), (2, 'Group'), (3, 'Both'), (4, 'Online')], default=2500, null=True),
        ),
    ]
