# Generated by Django 3.2.4 on 2021-09-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0037_alter_teacher_tuitionstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Avatar',
            field=models.ImageField(blank=True, default='../media/Avatar/Black_and_White_Shapes_and_Widgets_YouTube_Channel_Art12.png', null=True, upload_to='Avatar'),
        ),
    ]
