# Generated by Django 3.2.4 on 2021-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0038_alter_teacher_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Experience',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Experience',
            field=models.ManyToManyField(blank=True, null=True, related_name='Experience', to='Teacher.TeachingSection'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Preferred',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Preferred',
            field=models.ManyToManyField(blank=True, null=True, related_name='Preferred', to='Teacher.TeachingSection'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TuitionStyle',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Home tuition'), (2, 'Group'), (3, 'Course'), (4, 'Online'), (5, 'Group and Course'), (7, 'Home Tuition and Online'), (6, 'All')], default=2500, null=True),
        ),
    ]
