# Generated by Django 3.2.4 on 2021-09-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0039_auto_20210926_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Dhaka', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='PreferredArea',
            field=models.ManyToManyField(blank=True, null=True, to='Teacher.Areas'),
        ),
    ]
