# Generated by Django 3.2.4 on 2021-09-27 08:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0040_auto_20210927_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='PresentArea',
            field=models.ManyToManyField(blank=True, null=True, related_name='PresentArea', to='Teacher.Areas'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Graduation_Institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Graduation_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+880', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Post_Graduation_Institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PG_Institute', to='Teacher.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Post_Graduation_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PG_Subject', to='Teacher.subject'),
        ),
    ]
