# Generated by Django 3.2.4 on 2021-09-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0042_auto_20210927_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='StudentID',
            field=models.ImageField(blank=True, null=True, upload_to='SID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PresentArea',
            field=models.ForeignKey(blank=True, help_text='Select our zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PresentArea', to='Teacher.areas'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PresentLocation',
            field=models.CharField(blank=True, help_text='Full Address with house number', max_length=100, null=True),
        ),
    ]
