# Generated by Django 3.2.4 on 2021-09-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0043_auto_20210927_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Category',
            field=models.CharField(blank=True, choices=[(1, 'PUBLIC'), (2, 'NATIONAL'), (3, 'PRIVATE'), (4, 'OTHERS')], max_length=10, null=True),
        ),
    ]
