# Generated by Django 3.2.4 on 2021-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0044_university_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Cadet',
            field=models.BooleanField(default=False),
        ),
    ]
