# Generated by Django 3.2.4 on 2021-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0045_teacher_cadet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='HSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Education of Quran'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Education of Quran'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teachingsection',
            name='Preferred_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Education of Quran'), (8, 'Others')], default=1),
        ),
    ]
