# Generated by Django 3.2.4 on 2021-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0047_auto_20211003_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ReminderNote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
