# Generated by Django 3.2.4 on 2021-10-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0049_alter_university_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='HandWriting',
            field=models.SmallIntegerField(choices=[(1, 'Average'), (2, 'Good'), (3, 'Expert')], default=1),
        ),
    ]
