# Generated by Django 3.2.4 on 2021-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0051_alter_university_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSC_HSC_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Science', max_length=200)),
            ],
        ),
    ]
