# Generated by Django 3.2.4 on 2021-10-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0053_alter_teacher_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='HSC_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='HSC_SUB', to='Teacher.ssc_hsc_group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SSC_SUB', to='Teacher.ssc_hsc_group'),
        ),
    ]
