# Generated by Django 3.2.4 on 2021-10-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0054_auto_20211010_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HandWriting',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Average'), (2, 'Good'), (3, 'Expert')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Running_Tuition',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Normal'), (2, 'Special')], default=1, null=True),
        ),
    ]
