# Generated by Django 3.2.4 on 2021-10-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0056_teacher_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssc_hsc_group',
            old_name='Name',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='ssc_hsc_group',
            name='SHORT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
