# Generated by Django 3.2.4 on 2021-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0059_teacher_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='CoachingCenterName',
            field=models.CharField(blank=True, help_text='Fill if you are a coaching teacher', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Dance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Physiotherapist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ProfileWonerIs',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'School Teacher'), (2, 'College Teacher'), (3, 'University Teacher'), (4, 'Coaching Teacher')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Normal Child'), (2, 'Special Child')], default=1, null=True),
        ),
    ]
