# Generated by Django 3.2.4 on 2021-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0060_auto_20211017_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='IELTS',
            field=models.BooleanField(default=False),
        ),
    ]
