# Generated by Django 3.2.4 on 2021-10-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0062_alter_teachingsection_preferred_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
