# Generated by Django 3.2.4 on 2021-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0063_teacher_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='AbroadUniversity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Normal Child'), (2, 'Autistic/Special Child')], default=1, null=True),
        ),
    ]
