# Generated by Django 3.2.4 on 2021-10-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0064_auto_20211018_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='ProfileWonerIs',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ImATeacherOf',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'School'), (2, 'College'), (3, 'University'), (4, 'Coaching')], null=True),
        ),
    ]
