# Generated by Django 3.2.4 on 2021-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0065_auto_20211019_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='GMAT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='GRE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='MartialArts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TOFEL',
            field=models.BooleanField(default=False),
        ),
    ]
