# Generated by Django 3.2.4 on 2021-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0066_auto_20211019_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Oth_Graduation_Institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
