# Generated by Django 3.2.4 on 2021-10-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0067_teacher_oth_graduation_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150, null=True)),
                ('District', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Teacher.district')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='Emergency',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='PresentLocationDistrict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='PresentLocationDivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='PresentLocationThana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+880', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UpzillaMunicipality',
        ),
    ]
