# Generated by Django 3.2.4 on 2021-10-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0069_auto_20211023_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Teacher.division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='Name',
            field=models.CharField(blank=True, default='Dhaka', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Avatar'),
        ),
    ]
