# Generated by Django 3.2.4 on 2021-10-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0071_auto_20211023_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Hafiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Spoken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thana',
            name='District',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='Teacher.district'),
        ),
    ]
