# Generated by Django 3.2.4 on 2021-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0072_auto_20211024_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField(blank=True, choices=[(0, 'Nursery/Play/KG'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12'), (20, 'Others')], null=True)),
                ('Medium', models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (7, 'Education of Quran'), (8, 'Others')], null=True)),
                ('Subject', models.ManyToManyField(blank=True, null=True, to='Teacher.Subject')),
            ],
        ),
    ]
