# Generated by Django 3.2.4 on 2021-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0073_classessubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Admission',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Engineering'), (2, 'Medical'), (3, 'University'), (4, 'Cadet')], null=True),
        ),
        migrations.AlterField(
            model_name='classessubject',
            name='Class',
            field=models.IntegerField(blank=True, choices=[(0, 'Nursery/Play/KG'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9 / O Level'), (10, 'Class 10 / O Level'), (11, 'Class 11 / AS'), (12, 'Class 12 / A2'), (20, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teachingsection',
            name='Preferred_Education',
            field=models.SmallIntegerField(choices=[(0, 'Nursery/Play/KG'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9 / O Level'), (10, 'Class 10 / O Level'), (11, 'Class 11 / AS'), (12, 'Class 12 / A2'), (20, 'Others')], default=20),
        ),
    ]
