# Generated by Django 3.2.4 on 2021-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0074_auto_20211024_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='GMATPoint',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='GREPoint',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='IELTSPoint',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TOFELPoint',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ImATeacherOf',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'School'), (2, 'College'), (5, 'Madrasa'), (3, 'University'), (4, 'Coaching')], null=True),
        ),
    ]
