# Generated by Django 3.2.4 on 2021-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0075_auto_20211026_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='HSC_MEDIUM_Curriculum',
            field=models.IntegerField(blank=True, choices=[(1, 'Edexcel'), (2, 'Cambridge'), (3, 'IB'), (4, 'Others')], null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='SSC_MEDIUM_Curriculum',
            field=models.IntegerField(blank=True, choices=[(1, 'Edexcel'), (2, 'Cambridge'), (3, 'IB'), (4, 'Others')], null=True),
        ),
    ]
