# Generated by Django 3.2.4 on 2021-11-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0076_auto_20211026_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Guardian_phone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Phone',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='PreferredArea',
            field=models.ManyToManyField(blank=True, null=True, related_name='PreferredArea', to='Teacher.Thana'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Refer_phone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='thana',
            name='District',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='Teacher.district'),
        ),
    ]
