# Generated by Django 3.2.4 on 2021-11-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0077_auto_20211104_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='thana',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='classessubject',
            name='Medium',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='GMATPoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='GREPoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='HSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='IELTSPoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='SSC_MEDIUM',
            field=models.IntegerField(blank=True, choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TOFELPoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TuitionStyle',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Home tuition'), (2, 'Group'), (3, 'Course'), (4, 'Online'), (5, 'Group and Course'), (7, 'Home Tuition and Online'), (7, 'Home Tuition and Group'), (6, 'All')], default=2500, null=True),
        ),
        migrations.AlterField(
            model_name='teachingsection',
            name='Preferred_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasha Medium'), (6, 'Technical'), (8, 'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='thana',
            name='District',
            field=models.ForeignKey(default=67, on_delete=django.db.models.deletion.CASCADE, to='Teacher.district'),
        ),
    ]
