# Generated by Django 3.2.4 on 2021-12-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0032_sms_time'),
        ('Teacher', '0080_alter_thana_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='roughnotes',
            field=models.ManyToManyField(blank=True, to='FollowUp.RoughNote'),
        ),
    ]
