# Generated by Django 3.2.4 on 2021-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='3w6y', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
    ]
