# Generated by Django 3.2.4 on 2021-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0005_auto_20210821_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='8m7i', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='Note',
            field=models.ManyToManyField(blank=True, null=True, to='GuardianArea.Note'),
        ),
    ]
