# Generated by Django 3.2.4 on 2021-08-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0008_alter_child_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='9gdv', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='Expected_Subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GuardianArea.subject'),
        ),
    ]
