# Generated by Django 3.2.4 on 2021-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_alter_teacher_experience'),
        ('GuardianArea', '0009_auto_20210825_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='Expected_Subjects',
        ),
        migrations.AddField(
            model_name='child',
            name='Expected_Subjects',
            field=models.ManyToManyField(blank=True, null=True, to='Teacher.Subject'),
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='bv22', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
