# Generated by Django 3.2.4 on 2021-08-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0011_auto_20210826_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Free_Time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='a7gg', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
    ]
