# Generated by Django 3.2.4 on 2021-08-26 06:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0012_auto_20210826_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Teacher_Background',
            field=models.SmallIntegerField(choices=[(1, 'General'), (2, 'Science'), (3, 'Engineer'), (4, 'Medical'), (5, 'Arts'), (6, 'Commerce'), (7, 'Technical'), (8, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='3kzo', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8801', max_length=128, region=None),
        ),
    ]
