# Generated by Django 3.2.4 on 2021-08-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0013_auto_20210826_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='evgb', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
    ]
