# Generated by Django 3.2.4 on 2021-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0021_alter_child_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='5zvh', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
    ]
