# Generated by Django 3.2.4 on 2021-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0022_auto_20210829_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='zzwx', help_text='Do not change it', max_length=5, primary_key=True, serialize=False),
        ),
    ]
