# Generated by Django 3.2.4 on 2021-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0025_auto_20210831_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Teacher_Religion',
            field=models.IntegerField(blank=True, choices=[(0, 'Islam'), (1, 'Hinduism '), (2, 'Buddhism '), (3, 'Christianity'), (4, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='Education_Level',
            field=models.CharField(choices=[(1, 'Class 0'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 10'), (13, 'Diploma'), (14, 'Degree'), (15, 'Honors'), (16, 'O-Level'), (17, 'A-Level(AS)'), (19, 'pre-KG'), (17, 'KG'), (18, 'A-Level(A2)'), (20, 'Others')], default=20, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Education_Medium',
            field=models.CharField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasa Medium'), (7, 'Others')], default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Age',
            field=models.CharField(choices=[(0, '<20'), (1, '21-25'), (2, '26-35'), (3, '>35')], default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Background',
            field=models.CharField(choices=[(1, 'General'), (2, 'Science'), (3, 'Engineer'), (4, 'Medical'), (5, 'Arts'), (6, 'Commerce'), (7, 'Technical'), (8, 'English Medium'), (9, 'English Version'), (10, 'Other')], default=3, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Experience',
            field=models.CharField(choices=[(0, 'No experience needed'), (1, '1/2 years experience'), (2, '3/5 years experience'), (3, 'More than 5 years experience')], default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'All')], default=4, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Level',
            field=models.CharField(choices=[(0, 'Secondary'), (1, 'Higher Secondary'), (3, 'Honors'), (4, 'Others')], default=3, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Type',
            field=models.CharField(choices=[(1, 'Normal'), (2, 'Special')], default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Type',
            field=models.CharField(choices=[(1, 'Normal'), (2, 'Special')], default=1, max_length=40),
        ),
    ]
