# Generated by Django 3.2.4 on 2021-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0027_auto_20210909_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Education_Institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='Expected_Style',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Private'), (2, 'Group'), (3, 'Both'), (4, 'Online')], null=True),
        ),
    ]
