# Generated by Django 3.2.4 on 2021-09-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0028_auto_20210916_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardiandetails',
            name='Note',
        ),
    ]
