# Generated by Django 3.2.4 on 2021-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0030_child_teacher_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Teacher_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasa Medium'), (7, 'Others')], default=1),
        ),
    ]
