# Generated by Django 3.2.4 on 2021-09-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0031_alter_child_teacher_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
