# Generated by Django 3.2.4 on 2021-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0033_auto_20210920_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Expected_College',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='Expected_School',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='PerClass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='PerCourse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='child',
            name='Teacher_HSC_GOLD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='Education_Level',
            field=models.SmallIntegerField(choices=[(1, 'Class 0'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12'), (13, 'Diploma'), (14, 'Degree'), (15, 'Honors'), (16, 'O-Level'), (17, 'A-Level(AS)'), (19, 'pre-KG'), (18, 'KG'), (20, 'A-Level(A2)'), (21, 'SSC Examinee'), (21, 'SSC Examinee'), (20, 'Others')], default=20),
        ),
    ]
