# Generated by Django 3.2.4 on 2021-09-20 13:58

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0034_auto_20210920_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Education_Level',
            field=models.SmallIntegerField(choices=[(1, 'Class 0'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12'), (13, 'Diploma'), (14, 'Degree'), (15, 'Honors'), (16, 'O-Level'), (17, 'A-Level(AS)'), (19, 'pre-KG'), (18, 'KG'), (20, 'A-Level(A2)'), (21, 'SSC Examinee'), (21, 'SSC Examinee'), (20, 'Others')], default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='Expected_Salary',
            field=models.IntegerField(blank=True, help_text='0 for Negotiable', null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='Expected_Style',
            field=models.SmallIntegerField(choices=[(1, 'Home tuition'), (2, 'Group'), (3, 'Course'), (4, 'Online')], default=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='Free_Duration',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=3600), '01 Hour'), (datetime.timedelta(seconds=5400), '01H 30M'), (datetime.timedelta(seconds=7200), '02 Hour'), (datetime.timedelta(seconds=9000), '02H 30M'), (datetime.timedelta(seconds=10800), '03 Hour')], default=datetime.timedelta(seconds=5400), null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='Gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=2),
        ),
        migrations.AlterField(
            model_name='child',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+8801', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Background',
            field=models.SmallIntegerField(choices=[(1, 'General'), (2, 'Science'), (3, 'Engineer'), (4, 'Medical'), (5, 'Arts'), (6, 'Commerce'), (7, 'Technical'), (8, 'English Medium'), (9, 'English Version'), (10, 'Other'), (100, 'All')], default=100),
        ),
    ]
