# Generated by Django 3.2.4 on 2021-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0035_auto_20210920_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Canceled',
            field=models.BooleanField(default=False),
        ),
    ]
