# Generated by Django 3.2.4 on 2021-09-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0036_child_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='Confirmed',
            new_name='Paid',
        ),
    ]
