# Generated by Django 3.2.4 on 2021-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0038_auto_20211002_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Education_Level',
            field=models.SmallIntegerField(choices=[(1, 'Class 0'), (1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12'), (13, 'Diploma'), (14, 'Degree'), (15, 'Honors'), (16, 'O-Level'), (17, 'A-Level(AS)'), (19, 'pre-KG'), (18, 'KG'), (20, 'A-Level(A2)'), (21, 'SSC Examinee'), (21, 'SSC Examinee'), (20, 'Others')], default=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='Education_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasa Medium'), (7, 'Education of Quran'), (9, 'Any'), (8, 'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='Gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (4, 'Any'), (3, 'Other')], default=2),
        ),
        migrations.AlterField(
            model_name='child',
            name='Name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Age',
            field=models.SmallIntegerField(choices=[(0, '<20'), (1, '21-25'), (2, '26-35'), (3, '>35'), (4, 'Any')], default=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Background',
            field=models.SmallIntegerField(choices=[(1, 'General'), (2, 'Science'), (3, 'Engineer'), (4, 'Medical'), (5, 'Arts'), (6, 'Commerce'), (7, 'Technical'), (8, 'English Medium'), (9, 'English Version'), (10, 'Education of Quran'), (11, 'Other'), (100, 'Any')], default=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Male/Female')], default=4),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Level',
            field=models.SmallIntegerField(choices=[(0, 'Secondary'), (1, 'Higher Secondary'), (3, 'Honors'), (5, 'Masters'), (4, 'Others'), (6, 'Any')], default=3),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Medium',
            field=models.SmallIntegerField(choices=[(1, 'Bangla Medium'), (2, 'English Medium'), (3, 'English Version'), (4, 'Madrasa Medium'), (7, 'Education of Quran'), (9, 'Any'), (8, 'Others')], default=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='Teacher_Religion',
            field=models.IntegerField(blank=True, choices=[(0, 'Islam'), (1, 'Hinduism '), (2, 'Buddhism '), (3, 'Christianity'), (4, 'Others'), (5, 'Any')], default=5, null=True),
        ),
    ]
