# Generated by Django 3.2.4 on 2021-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0042_guardiandetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiandetails',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
