# Generated by Django 3.2.4 on 2021-11-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0043_guardiandetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiandetails',
            name='Phone',
            field=models.CharField(default='+8801', max_length=20, unique=True),
        ),
    ]
