# Generated by Django 3.2.4 on 2021-12-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0046_auto_20211202_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Tuition', 'verbose_name_plural': 'Tuition`s'},
        ),
        migrations.AlterField(
            model_name='childgroup',
            name='Child',
            field=models.ManyToManyField(blank=True, to='GuardianArea.Child', verbose_name='Tuition'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='Child',
            field=models.ManyToManyField(blank=True, to='GuardianArea.Child', verbose_name='Tuition'),
        ),
        migrations.AlterField(
            model_name='guardiandetails',
            name='Child_Group',
            field=models.ManyToManyField(blank=True, to='GuardianArea.ChildGroup', verbose_name='Tuition Group'),
        ),
    ]
