# Generated by Django 3.2.4 on 2021-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0047_auto_20211207_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
