# Generated by Django 3.2.4 on 2021-12-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0048_child_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='Guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GuardianArea.guardiandetails'),
        ),
    ]
