# Generated by Django 3.2.4 on 2021-08-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0001_initial'),
        ('FollowUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianhistory',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='GuardianArea.child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianhistory',
            name='Guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.guardiandetails'),
        ),
        migrations.AddField(
            model_name='permanenttuitionforteacher',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherhistory',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarytuitionforchild',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
        ),
        migrations.AddField(
            model_name='user',
            name='Guardian',
            field=models.ManyToManyField(blank=True, to='GuardianArea.GuardianDetails'),
        ),
    ]
