# Generated by Django 3.2.4 on 2021-08-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_alter_teacher_rating'),
        ('GuardianArea', '0003_alter_child_slug'),
        ('FollowUp', '0002_auto_20210806_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListedTuitionForChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child')),
                ('Teacher', models.ManyToManyField(to='Teacher.Teacher')),
            ],
        ),
    ]
