# Generated by Django 3.2.4 on 2021-08-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_alter_teacher_rating'),
        ('GuardianArea', '0004_alter_child_slug'),
        ('FollowUp', '0003_shortlistedtuitionforchild'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermanentTuitionForTeacher',
            new_name='PermanentTuitionForChild',
        ),
    ]
