# Generated by Django 3.2.4 on 2021-08-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0020_alter_child_slug'),
        ('Teacher', '0008_auto_20210826_0624'),
        ('FollowUp', '0004_rename_permanenttuitionforteacher_permanenttuitionforchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytuitionforchild',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child', unique=True),
        ),
        migrations.CreateModel(
            name='AssignedTeacherForChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child')),
                ('Teacher', models.ManyToManyField(to='Teacher.Teacher')),
            ],
        ),
    ]
