# Generated by Django 3.2.4 on 2021-08-28 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0006_permanenttuitionforchild_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanenttuitionforchild',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
