# Generated by Django 3.2.4 on 2021-08-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0008_alter_shortlistedtuitionforchild_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanenttuitionforchild',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
