# Generated by Django 3.2.4 on 2021-08-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0025_auto_20210831_1139'),
        ('FollowUp', '0009_permanenttuitionforchild_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedtuitionforchild',
            name='Child',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
        ),
        migrations.AlterField(
            model_name='temporarytuitionforchild',
            name='Child',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Job_Title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
