# Generated by Django 3.2.4 on 2021-09-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0014_auto_20210919_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanenttuitionforchild',
            name='Reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
