# Generated by Django 3.2.4 on 2021-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0016_alter_assignedteacherforchild_talks'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytuitionforchild',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedteacherforchild',
            name='Talks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
