# Generated by Django 3.2.4 on 2021-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0017_auto_20210919_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarytuitionforchild',
            old_name='json',
            new_name='TalksJson',
        ),
        migrations.AddField(
            model_name='assignedteacherforchild',
            name='TalksJson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanenttuitionforchild',
            name='TalksJson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortlistedtuitionforchild',
            name='TalksJson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
