# Generated by Django 3.2.4 on 2021-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0019_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
