# Generated by Django 3.2.4 on 2021-09-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0020_alter_reminder_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='Note',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
