# Generated by Django 3.2.4 on 2021-10-13 05:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0022_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8801796693300', max_length=128, region=None),
        ),
    ]
