# Generated by Django 3.2.4 on 2021-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0026_alter_user_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanenttuitionforchild',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
