# Generated by Django 3.2.4 on 2021-12-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0048_child_active'),
        ('Teacher', '0080_alter_thana_district'),
        ('FollowUp', '0027_permanenttuitionforchild_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTeacherForChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talks', models.CharField(blank=True, max_length=200, null=True)),
                ('TalksJson', models.JSONField(blank=True, null=True)),
                ('Child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child')),
                ('Teacher', models.ManyToManyField(to='Teacher.Teacher')),
            ],
        ),
    ]
