# Generated by Django 3.2.4 on 2021-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0028_demoteacherforchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoteacherforchild',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
