# Generated by Django 3.2.4 on 2021-12-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0050_auto_20211219_1345'),
        ('FollowUp', '0029_demoteacherforchild_permanent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoughNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.JSONField(blank=True, null=True)),
                ('Child', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child')),
            ],
        ),
    ]
