# Generated by Django 3.2.4 on 2021-12-20 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GuardianArea', '0050_auto_20211219_1345'),
        ('FollowUp', '0030_roughnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='roughnote',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roughnote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FollowUp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardianhistory',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roughnote',
            name='Child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GuardianArea.child'),
        ),
    ]
