# Generated by Django 3.2.4 on 2021-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FollowUp', '0031_auto_20211220_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
